on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for react-app3 (Tagged with run ID)
        run: |
          RUN_ID=${{ github.run_id }}
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/react-app3
          BUILD_TAG=$IMAGE_NAME:$RUN_ID
          LATEST_TAG=$IMAGE_NAME:latest
          # Build and push images
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push -t $BUILD_TAG -t $LATEST_TAG .

      - name: SSH to Server and Deploy react-app3
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            RUN_ID=${{ github.run_id }}
            IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/react-app3
            docker network create --driver bridge react-network || true
            docker pull $IMAGE_NAME:$RUN_ID
            docker stop react-app3 || true
            docker rm react-app3 || true
            docker run -d --name react-app3 -p 4001:80 \
              --network react-network \
              $IMAGE_NAME:$RUN_ID
            docker system prune -f --volumes
