name: Deploy React App with Rollback on Failure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build & push the v2 image
      - name: Build and Push v2 Docker Image
        run: |
          docker build -t vk2615/hello-world-1:v2 .
          docker push vk2615/hello-world-1:v2

      # SSH into the server and deploy v2
      - name: Deploy v2 to Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Checking if v1 is running..."
            V1_STATUS=$(docker service ls | grep "hello-world-app" | wc -l)
            
            if [ "$V1_STATUS" -eq "0" ]; then
              echo "v1 is missing! Deploying v1..."
              docker service create --name hello-world-app --publish 4000:80 vk2615/hello-world-1:v1
              sleep 10
            fi
            
            echo "Pulling latest v2 image..."
            docker pull vk2615/hello-world-1:v2 || { echo "Failed to pull v2 image"; exit 1; }

            echo "Deploying v2..."
            docker service update --force --image vk2615/hello-world-1:v2 hello-world-app || { 
              echo "Deployment failed! Rolling back to v1..."
              docker service update --force --image vk2615/hello-world-1:v1 hello-world-app
              exit 1
            }

      # Send Slack Notification
      - name: Send Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "✅ Deployment of v2 was successful! 🚀"

      - name: Send Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "⚠️ Deployment of v2 failed! Rolling back to v1! 🔄"
